### ISSUE TITLE
Define asn1 for CompositeDigest ?

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-ounsworth-composite-sigs#41]
We will run into applications where a message digest is passed externally to the signature (for example in CMS).

Is it right to define a CompositeDigest here so that we don't need to go extending / updating other standards?

**Comment by ounsworth** [comment]
Related to #31

**Comment by csosto-pk** [comment]
Do we need multiple digests? I mean a digest digests the big blob that is about to be signed with various algorithms by the CA.  I don't think we need to digest the blob with more than one algorithms, do we?

**Comment by danvangeest** [comment]
> Do we need multiple digests? I mean a digest digests the big blob that is about to be signed with various algorithms by the CA. I don't think we need to digest the blob with more than one algorithms, do we?

In the CA case there could be multiple digests (e.g. ecdsaWithSHA384 + LMS (using SHA256 or Intrinsic depending on your perspective)).  However those digests types aren't reported separately, they're always reported in combination with the signature algorithm.  So the CA does doesn't really apply here.  I've only seen the CMS case which applies here, where there are separate SignatureAlgorithmIdentifier and DigestAlgorithmIdentifier fields rather than a combined signature+digest field like X.509.  CMS' SignatureAlgorithmIdentifier can also be a signature+digest, so the digest type is actually duplicated.

**Comment by csosto-pk** [comment]
The more I see the complications between CMS and PKIX the more I am starting to think these should be separate because the draft is getting overcomplicated. 

https://tools.ietf.org/html/draft-ietf-lamps-pkix-shake and https://tools.ietf.org/html/draft-ietf-lamps-cms-shakes do something similar by breaking up these identifiers for PKIX and CMS separately.

**Comment by ounsworth** [comment]
I am removing this ticket from the IETF105 milestone.

Let's get the basic draft published, and we can deal with CMS concerns later.
