### ISSUE TITLE
Strengthen security properties of composite signature primitive

### ISSUE THREAD

**Issue by sergemister** [EntrustCorporation/draft-ounsworth-composite-sigs#63]
So far I've been thinking of the composite signature algorithm only in the context of the related algorithm and key parameters, but it occurred to me that we probably should consider the properties of the signature primitive on its own.  Specifically, currently if one has a composite signature where three algorithms have been applied, one could change it into a valid signature where only two algorithms have been applied.  This seems an undesirable property; it would be safer if none of the component signatures were valid if separated from the others.

As a strawman, maybe this is achieved by prepending the signature algorithm list to the message to be signed before calling the component signature algorithms.  You can still extract a valid component signature, but at least it's on a (hopefully) meaningless message.  You could go further by generating a nonce, hashing the nonce, algorithm list, and message, then signing that with the component signature algorithms.  Now an attacker can't predict the value that will be signed with the component signature algorithms.

This is certainly adding complexity; is there a security benefit?  Maybe we should try to define the security properties we want the composite signature algorithm to have.

**Comment by ounsworth** [comment]
I thought that in PKIX objects (X.509, CMS), the AlgorithmID (and params) went into the document before being signed, solving this problem. ..?

**Comment by ounsworth** [comment]
- [ ] ACTION: @sergemister to write up an EDNOTE paragraph to put in the Security Considerations section.

_(Feel free to post the paragraph here, and I'll insert it into the doc)_

**Comment by sergemister** [comment]
Here's what I'm thinking for an EDNOTE in the Security Considerations section:

EDNOTE: Two aspects of the proposed scheme may warrant more attention from a security perspective.  Firstly, while the component public keys may have associated parameters, those parameters are moved to the public key value portion of the resulting composite public key object.  This may be safer, as https://csrc.nist.gov/csrc/media/publications/conference-paper/1996/10/22/proceedings-of-the-19th-nissc-1996/documents/paper075/paper.pdf describes an attack where the parameters are kept separate from the key value.  But the implications should be carefully considered.  Secondly, the basic composite signature primitive should be analyzed on its own.  For example, as currently described a valid component signature can be extracted from a composite signature.  The X.509 data being signed makes it unlikely that the extracted signature would have value, but it may be preferable to ensure that a requester cannot control the signature value signed with a component signature algorithm when requesting a composite signature.

**Comment by sergemister** [comment]
Not for the security considerations section, but I also think we should understand the parameter inheritance described in ISO X.509 (2016) (also mentioned in the paper cited in my previous comment):

"Also, note that if the public key value used as input to the hash function has been extracted from a public-key certificate, then it is possible (e.g., if parameters for the digital signature algorithm were inherited) that this may not be sufficient input for the HASH."
Does this inheritance affect our proposal?

**Comment by jogray72** [comment]
We had a discussion about this today.   Since the composite signature is just a concatenation of the components, any signature component can be removed and the signature reconstructed such that the object that was signed would be able to be validated with a single component.   The validator would not know that the signature was really supposed to be a composite signature.    The reverse is also true, two separate algorithms that have signed the same object could be taken and used to construct a composite signature that was considered valid.   A stronger binding between the two composite signatures is need so that a single components signature over ToBeSignedData does not match its concatenated portion of the ToBeSignedData.

**Comment by danvangeest** [comment]
> The validator would not know that the signature was really supposed to be a composite signature.

In X.509 at least, the identifier defined by our SIGNATURE-ALGORITHM is part of the signed data.
```
  TBSCertificate  ::=  SEQUENCE  {
      version         [0]  Version DEFAULT v1,
      serialNumber         CertificateSerialNumber,
      signature            AlgorithmIdentifier{SIGNATURE-ALGORITHM,
                                {SignatureAlgorithms}},
...
```
and our SIGNATURE-ALGORITHM has the list of component algorithms in the identifier's required params.  So in this case the validator would know that the signature is supposed to be a composite signature.

Similarly in the reverse, since the SIGNATURE-ALGORITHM params are signed, two signatures on the same data can't be combined into a composite signature because the signed data would be necessarily modified to change the signature identifier to composite and add the correct params.

If any other protocol or encoding doesn't sign the signature identifier with params, that seems like an issue with that specification, not with composite signatures, since the specification itself could be subject to some kind of substitution attack.

I feel like I'm missing something here... are we trying to protect the case where the signed data doesn't contain the signature algorithm identifier?

**Comment by ounsworth** [comment]
> If any other protocol or encoding doesn't sign the signature identifier with params, that seems like an issue with that specification, not with composite signatures, since the specification itself could be subject to some kind of substitution attack.

See @sergemister , @danvangeest has the same opinion that I do! This ought to be a protocol problem, not a signature alg problem. I also agree that all the PKIX-like protocols that I can think of off the top of my head include signature alg params in the signed data.

I do, however, think this warrants a note in the Security Considerations section; ie taking two single-signed documents and combining them into a valid dual-signed document (or vice-versa: splitting a dual-signed document into two single-signed docs) is a new type of attack that that becomes relevant when using Composite that nobody had to think about before, so it's worth calling it out

**Comment by sergemister** [comment]
I'll start by saying that I have mixed thoughts on this.  In raising the ticket I am looking to raise awareness and have the group consider the question, which I guess I am achieving :)  If we declare that the component keys of a composite key MUST be created for use in the composite key and MUST NOT be used on their own, then maybe this concern doesn't apply.

Having said that, let me defend the idea a bit.  There are some examples of protocols where the parameters are not signed (I'm reading the specs quickly, hopefully I have it right):

PKCS#10 (https://tools.ietf.org/html/rfc2986):

```
   CertificationRequestInfo ::= SEQUENCE {
        version       INTEGER { v1(0) } (v1,...),
        subject       Name,
        subjectPKInfo SubjectPublicKeyInfo{{ PKInfoAlgorithms }},
        attributes    [0] Attributes{{ CRIAttributes }}
   }

   ...
   
   CertificationRequest ::= SEQUENCE {
        certificationRequestInfo CertificationRequestInfo,
        signatureAlgorithm AlgorithmIdentifier{{ SignatureAlgorithms }},
        signature          BIT STRING
   }

   ...


          signature is the result of signing the certification request
          information with the certification request subject's private
          key.
```

I didn't see any hint that the attributes would normally contain the signature algorithm, and I manually checked an OpenSSL-generated request to confirm.  This isn't the best example because what is being signed is the key that is used to sign the signature, but nonetheless, I think it's a valid example, and is still in use.

Cryptographic Message Syntax (https://tools.ietf.org/html/rfc5652#section-5.4)

It's easiest to study the case where no signed attributes are present:
```
	5.4.  Message Digest Calculation Process

	   ...
	   
	   When the signedAttrs field is absent, only the octets comprising the
	   value of the SignedData encapContentInfo eContent OCTET STRING (e.g.,
	   the contents of a file) are input to the message digest calculation.
```
When signedAttrs are present, still from section 5.4:

```
   When the field is present, however, the result is the message
   digest of the complete DER encoding of the SignedAttrs value
   contained in the signedAttrs field.  Since the SignedAttrs value,
   when present, must contain the content-type and the message-digest
   attributes, those values are indirectly included in the result.
```   
But again I don't think the signature algorithm is necessarily present in the message being signed as it isn't necessarily in the signed attributes.

**Comment by danvangeest** [comment]
For `CertificationRequestInfo`, the list of keys in the `subjectPKInfo` field would have to correspond to the signature params, so you couldn't add or remove signature components.  But since the signature algorithm identifier isn't signed itself, perhaps you could get away with swapping a signature component, e.g. replace an `ecdsa-with-SHA256` component with a `ecdsa-with-SHA1` component, for whatever advantage that would give you.  But this looks like a general problem with CSRs, not specific to composite signatures because you could just do the same thing with a single ecdsa-with-SHA256 signature CSR.

In CMS they added a signed attribute to explicitly deal with this sort of thing: [RFC 6211](https://tools.ietf.org/html/rfc6211).
```
      CMSAlgorithmProtection ::= SEQUENCE {
          digestAlgorithm         DigestAlgorithmIdentifier,
          signatureAlgorithm  [1] SignatureAlgorithmIdentifier OPTIONAL,
          macAlgorithm        [2] MessageAuthenticationCodeAlgorithm
                                           OPTIONAL
      }
      (WITH COMPONENTS { signatureAlgorithm PRESENT,
                         macAlgorithm ABSENT } |
       WITH COMPONENTS { signatureAlgorithm ABSENT,
                         macAlgorithm PRESENT })
```
Here, `signatureAlgorithm` is optional, so this attribute would have to be used correctly with composite signatures.

**Comment by ounsworth** [comment]
Re-discussed with @jogray72 .
This is still a valid comment: currently we have wording in the draft that you should not re-use keys between single-alg and composite keys / certs. If we did what Serge is suggesting and include the signature alg id in the signed data automatically, then that would relax that requirement.

**Comment by johngray-dev** [comment]
We have included the Signature Algorithm ID (OID) in DER format with the Message before it is signed (since version 10).  It achieves a weak non-separability.

**Comment by johngray-dev** [comment]
Group agreed we can close, we are claiming weak non-separability as per Bindel-Hale which we reference.
